sudo: false

language: node_js
node_js:
  - "7"
  - "6"

install:
  - npm install

before_script:
  - npm install -g gulp

script: gulp test

cache: yarn

notifications:
  email:
    on_success: never
    on_failure: always
